### ISSUE TITLE
Audio Que's

### ISSUE THREAD

**Issue by ReinQuest** [Ian0526/SnatchinBracken#6]
I was wondering how hard it would be to put a seconds timer on the "CrackNeck" audio play. For people making sound mods to start playing the audio earlier so that it finishes before player death.

**Comment by ReinQuest** [comment]
Also a suggestion, Instakill When Alone, maybe change default to false.

**Comment by Ian0526** [comment]
Someone could make a Harmony patch for the AudioSource object called crackNeckAudio implementing a timer before it fully executes. This wouldn't have an effect on my mod at all. I'm leaving that as is because it just plays when the player actually dies which I believe is fine.

-- and I agree about making that false, someone told me otherwise but multiple people have mentioned it's confusing.

**Comment by Ian0526** [comment]
Added in this update. Closing, feel free to open it back up if you want to discuss the sound stuff further.
